import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/context/contextprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "w-full h-screen overflow-hidden bg-[url('/site-bg.svg')]   text-white bg-cover bg-no-repeat relative"
        }
      >
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
